# rhc-worker-playbook configuration

# recipient directive to register with dispatcher
directive = "rhc-worker-playbook"

# whether to verify incoming playboks
verify_playbook = true

# whether the playbook verification should ensure latest insights-core version
verify_playbook_version_check = true

# perform the insights-client GPG check on the insights-core egg
insights_core_gpg_check = true
